/**
 *  TiledMapObject.java
 *  Created on Jan 22, 2014 9:26:39 PM for project saga
 *  Author: psy_wombats
 *  Contact: psy_wombats@wombatrpgs.net
 */
package net.wombatrpgs.saga.maps;

import java.lang.reflect.Field;
import java.util.Iterator;

import net.wombatrpgs.mgns.core.MainSchema;
import net.wombatrpgs.saga.core.SGlobal;
import net.wombatrpgs.saga.maps.events.EventType;

import com.badlogic.gdx.maps.MapObject;

/**
 * A MGN wrapper for the LibGDX MapObject. Immutable.
 */
public class TiledMapObject {
	
	/** Properties in for Tiled map objects */
	// these ones are hard-coded by libgdx (the bastards)
	public static final String PROPERTY_X = "x";
	public static final String PROPERTY_Y = "y";
	// mgn-specific
	public static final String PROPERTY_Z = "z";
	public static final String PROPERTY_ID = "id";
	public static final String PROPERTY_TYPE = "type";
	public static final String PROPERTY_KEY = "key";
	
	protected final LoadedLevel parent;
	protected final MapObject object;
	
	/**
	 * Creates a new wrapper for the given Tiled map object.
	 * @param	parent			The level this object is associated with
	 * @param	object			The libgdx/tiled object to wrap
	 */
	public TiledMapObject(LoadedLevel parent, MapObject object) {
		this.parent = parent;
		this.object = object;
	}
	
	/** @return The parent level of this tiled map object */
	public LoadedLevel getLevel() { return parent; }
	
	/** @return The string value of the provided key */
	public String getString(String key) { return object.getProperties().get(key, String.class); }
	
	/** @return The integer value of the provided key */
	public int getInt(String key) { return object.getProperties().get(key, Integer.class); }
	
	/** @return The x-coord of this object on the map (in pixels) */
	public int getX() { return getInt(PROPERTY_X); }
	
	/** @return The y-coord of this object on the map (in pixels) */
	public int getY() { return getInt(PROPERTY_Y); }
	
	/** @return The x-coord of this object on the map (in tiles) */
	public int getTileX() { return getX() / parent.getTileWidth(); }
	
	/** @return The y-coord of this object on the map (in tiles) */
	public int getTileY() { return getY() / parent.getTileWidth(); }
	
	/**
	 * Reads the map object's event type from its property list. Reports a
	 * problem if the event has no event type.
	 * @return
	 */
	public EventType getType() {
		String value = getString(PROPERTY_TYPE);
		EventType result;
		if (value == null) {
			SGlobal.reporter.err("No event type for map object " + this + " on map " + parent);
			return null;
		}
		try {
			result = EventType.valueOf(value);
		} catch (IllegalArgumentException e) {
			SGlobal.reporter.err(value + " is not a possible event type for " + this, e);
			return null;
		}
		return result;
	}
	
	/**
	 * Attempts to generate an MDO for this object as if it was of the type
	 * provided. This involves a lot of reflection; essentially what happens is
	 * it attempts to map all properties to similarly-named fields in the MDO.
	 * @param	clazz			The class of MDO to generate
	 * @return					An instance of that MDO, with fields filled in
	 */
	public <T extends MainSchema> T generateMDO(Class<T> clazz) {
		
		T mdo;
		try {
			mdo = clazz.newInstance();
		} catch (Exception e) {
			SGlobal.reporter.err("reflect-instantiate failed, ughhhhh", e);
			return null;
		}
		mdo.description = "Autogenerated by TiledMapObject.generateMDO";
		mdo.name = object.toString();
		
		// let's assign all values found on the object here
		Iterator<String> keys = object.getProperties().getKeys();
		while (keys.hasNext()) {
			String key = keys.next();
			if (key.equals(PROPERTY_X)) continue;
			if (key.equals(PROPERTY_Y)) continue;
			if (key.equals(PROPERTY_TYPE)) continue;
			try {
				Field field = clazz.getField(key);
				try {
					Object value = object.getProperties().get(key, field.getType());
					field.set(mdo, value);
				} catch (Exception e) {
					SGlobal.reporter.warn("Bad field value " +
							object.getProperties().get(key) +
							" for object " + object +
							" on map " + parent);
				}
			} catch (Exception e) {
				SGlobal.reporter.warn("Bad field " + key + " on Tiled object " +
						object + " on map " + parent);
			}
		}
		
		return mdo;
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return (object.getName() == null) ? "anon event" : object.getName();
	}

}
