sceneSwitch('finale_stop', true)
walk('hero', 4, 'NORTH')
wait(2)
pan(0, 7)
wait(3)
speak("I couldn't do it. You and I are strangers, but I feel like that you are me, almost. In this new, greener world, everything feels connected. If you think our wonderful creature is best left on Luna...")
speak("Then I must accept.")
speak("Now all that remains is to... turn off the collider. To kill Him? No...")
wait(2)
speak("Hurry! Throw the switch! Before my willpower fades!")
wait(.5)
walk('hero', 1, 'NORTH')
wait(1)
playSound('switch')
sceneSwitch('finale_fade2', true)
wait(.5)
walk('hero', 1, 'SOUTH')
face('hero', 'NORTH')
wait(4)
speak("Am I free?")
speak("I feel like I've lost so much in that other place, that wonderful lively place. And now to be back here, I...")
speak("But you're here now. Another living creature.")
speak("I am free.")
wait(1)
tint(0, 0, 0, 2)
wait(2)
sceneSwitch('all_done', true)
outro()
