sceneSwitch('finale_stop', true)
walk('hero', 4, 'NORTH')
wait(2)
pan(0, 7)
wait(3)
speak("Well done. Very well done. I regret that I failed, but I'm glad you succeeded.")
speak("I suppose you know what I am, now. Sitting under the collider, watching you... I've felt very strange for a while, and now that the collider is active again, I'm not even sure which world I belong to any more.")
speak("If you throw that switch, the collider goes down. The experiment will die. And now I'll die with it.")
wait(2)
speak("Well, what are you waiting for? If you don't hurry, you'll be affected too. Don't hesitate.")
wait(1)
walk('hero', 1, 'NORTH')
wait(1)
playSound('switch')
wait(.5)
sceneSwitch('finale_fade', true)
wait(4)
walk('hero', 10, 'SOUTH')
wait(2)
tint(0, 0, 0, 2)
wait(2)
sceneSwitch('all_done', true)
outro();
