package net.wombatrpgs.rainfall;

import net.wombatrpgs.mgne.data.Database;
import net.wombatrpgs.mgne.data.DirectoryDataLoader;
import net.wombatrpgs.mgne.global.DebugReporter;
import net.wombatrpgs.mgne.global.SimpleFileLoader;
import net.wombatrpgs.mgne.global.Global;
import net.wombatrpgs.rainfallschema.WindowDataMDO;

import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * Autogenerated by project setup.
 */
public class Main {
	
	/**
	 * Main launcher. Autogenerated.
	 * @param 	args		Unusused
	 */
	public static void main(String[] args) {
		
		// TODO: set up a loading bar or something
		Global.reporter = new DebugReporter();
		Global.fileLoader = new SimpleFileLoader();
		Global.dataLoader = new DirectoryDataLoader();
		Global.mapper = new ObjectMapper();
		Global.data = new Database();
		Global.dataLoader.addToDatabase("res/data");
		
		WindowDataMDO data = (WindowDataMDO) Global.data.getEntryByKey("window_data");
		
		LwjglApplicationConfiguration cfg = new LwjglApplicationConfiguration();
		cfg.title = data.windowName;
		cfg.useGL20 = false;
		cfg.width = data.defaultWidth;
		cfg.height = data.defaultHeight;
		
		new LwjglApplication(new RainfallGame(), cfg);
	}
}
