package net.wombatrpgs.rainfall;

import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;

/**
 * Autogenerated by project setup.
 */
public class Main {
	
	public static final String WARMUP_NAME = "One second...";
	public static final int WARMUP_WIDTH = 320;
	public static final int WARMUP_HEIGHT = 240;
	
	/**
	 * Main launcher. Autogenerated at one point.
	 * @param 	args		Unusused
	 */
	public static void main(String[] args) {
		
		LwjglApplicationConfiguration cfg = new LwjglApplicationConfiguration();
		cfg.title = WARMUP_NAME;
		cfg.useGL20 = false;
		cfg.width = WARMUP_WIDTH;
		cfg.height = WARMUP_HEIGHT;
		
		new LwjglApplication(new RainfallGame(new DesktopFocusReporter()), cfg);
	}
}
