package net.wombatrpgs.saga.client;

import net.wombatrpgs.mrogue.SagaGame;
import net.wombatrpgs.mrogue.core.MRogueGame;
import net.wombatrpgs.mrogue.core.Platform;

import com.badlogic.gdx.ApplicationListener;
import com.badlogic.gdx.backends.gwt.GwtApplication;
import com.badlogic.gdx.backends.gwt.GwtApplicationConfiguration;

/**
 * More autogenerated stuff from the setup UI.
 */
public class GwtLauncher extends GwtApplication {
	
	public static final String WARMUP_NAME = "One moment please...";
	public static final int WARMUP_WIDTH = 320;
	public static final int WARMUP_HEIGHT = 240;
	
	@Override
	public GwtApplicationConfiguration getConfig () {
		GwtApplicationConfiguration cfg = new GwtApplicationConfiguration(
				WARMUP_WIDTH, WARMUP_HEIGHT);
		cfg.stencil = true;
		return cfg;
	}

	@Override
	public ApplicationListener getApplicationListener () {
		return new SagaGame();
//		return new MRogueGame(new Platform() {
//			
//		});
	}
}