/**
 *  DatabaseEntrySchemaException.java
 *  Created on Aug 6, 2012 3:55:59 AM for project MGNSE
 *  Author: psy_wombats
 *  Contact: psy_wombats@wombatrpgs.net
 */
package net.wombatrpgs.mgnse.exception;

/**
 * An exception for the general class of errors that involve an existing
 * database entry not matching up with its specified schema. Usually the
 * result of out-of-synch database and schema.
 */
public class DatabaseEntrySchemaException extends Exception{

	public DatabaseEntrySchemaException(String string) {
		super(string);
	}

	/** some autogenerated shit */
	private static final long serialVersionUID = -6596075905442945782L;

}
