/**
 *  SoundObject.java
 *  Created on Mar 24, 2013 1:42:28 AM for project rainfall-libgdx
 *  Author: psy_wombats
 *  Contact: psy_wombats@wombatrpgs.net
 */
package net.wombatrpgs.mgne.io.audio;

import com.badlogic.gdx.assets.AssetManager;
import com.badlogic.gdx.audio.Sound;

import net.wombatrpgs.mgne.core.MGlobal;
import net.wombatrpgs.mgneschema.audio.SoundMDO;
import net.wombatrpgs.mgneschema.audio.data.RepeatType;

/**
 * A sound effect map object.
 */
public class SoundObject extends AudioObject {
	
	protected SoundMDO mdo;
	protected transient Sound coreSound;

	/**
	 * Constructs a sound object for another object from data.
	 * @param	mdo				The data to create from
	 */
	public SoundObject(SoundMDO mdo) {
		super(mdo);
		this.mdo = mdo;
	}
	
	/**
	 * @see net.wombatrpgs.mgne.core.interfaces.Updateable#update(float)
	 */
	@Override
	public void update(float elapsed) {
		// Nothing?
	}

	/**
	 * @see net.wombatrpgs.mgne.graphics.interfaces.Disposable#dispose()
	 */
	@Override
	public void dispose() {
		if (MGlobal.assets.isLoaded(filename)) {
			MGlobal.assets.unload(filename);
		}
	}
	
	/**
	 * Creates a new sound object by whipping an MDO out of a filename. Assumes
	 * no repeat and maybe some other default settings.
	 * @param	filename		The name of the sound file to load
	 * @return					A new sound object for that sound
	 */
	public static SoundObject createFromFile(String filename) {
		SoundMDO soundMDO = new SoundMDO();
		soundMDO.description = "Generated by file: " + filename;
		soundMDO.file = filename;
		soundMDO.name = "anonymous sound (" + filename + ")";
		soundMDO.repeats = RepeatType.PLAY_ONCE;
		soundMDO.volume = 100;
		return new SoundObject(soundMDO);
	}

	/**
	 * @see net.wombatrpgs.mgne.io.audio.AudioObject#corePlay()
	 */
	@Override
	protected void corePlay() {
		long id = coreSound.play((float) mdo.volume / 100.f);
		coreSound.setLooping(id, mdo.repeats == RepeatType.LOOP);
	}

	/**
	 * Note this stops all playing instances.
	 * @see net.wombatrpgs.mgne.io.audio.AudioObject#coreStop()
	 */
	@Override
	protected void coreStop() {
		coreSound.stop();
	}

	/**
	 * @see net.wombatrpgs.mgne.io.audio.AudioObject#getLoaderClass()
	 */
	@Override
	protected Class<?> getLoaderClass() {
		return Sound.class;
	}

	/**
	 * @see net.wombatrpgs.mgne.io.audio.AudioObject#postAudioProcessing
	 * (com.badlogic.gdx.assets.AssetManager)
	 */
	@Override
	protected void postAudioProcessing(AssetManager manager) {
		coreSound = (Sound) manager.get(filename, getLoaderClass());
	}

}
