local hero1 = getHero(0).getName()
local hero2 = getHero(1).getName()
local hero3 = getHero(2).getName()
local hero4 = getHero(3).getName()

speak(hero4, "Is he alive?")
speak("Champion", "Monsters from the southern mountains... They came too fast...")
speak(hero2, "Hold on, man!")
speak("Champion", "They took the everburning torch... You must avenge us.")
sceneSwitch('champion_dead', true)
speak(hero2, "He's dead.")
speak(hero3, "Rest in peace.")
