local hero = getHero(0).getName()

speak("Elder", hero .. ", it's good you came. Before you leave, I wanted to tell you a story. You know the legend of Hero, correct?")
speak(hero, "Of course, the city was sealed by magic after monsters came from the other worlds.")
speak("Elder", "There is more. Many say that before the sages sealed the gates of Hero, they opened a back entrance with four otherworldly artifacts.")
speak(hero, "That's the legend.")
speak("Elder", "I'm one of the few alive who remember when the gates were sealed, so I know it happened.")
speak("Elder", "In fact, they gave each of the city elders one of the four otherworldly artifacts, so if we wished, we could reopen the way to Hero.")
speak(hero, "So you have one of these artifacts?")
speak("Elder", "Yes. My artifact is actually a set of items, magical sending stones that let the owners talk across great distances.")
speak("Elder", "I gave one of these sending stones to my son, David. Against my wishes, he ran away to find Hero himself. I can't hear David on my stone any more.")
speak(hero, "So something happened to him?")
speak("Elder", "I don't know. If you can find David, I will gladly give you a sending stone.")
speak(hero, "Thank you, Elder.")
speak("Elder", "The last time I heard from David, he was on his way to the river city. See if you can find him there. Remember, you'll need all four artifacts to enter Hero.")
sceneSwitch('opening_talked_elder', true)
