local hero = getHero(0).getName()

speak("Elder", hero .. ", it's good you came. Before you leave, I wanted to tell you a story. You know the legend of Hero, correct?")
speak(hero, "Of course, the city was sealed by magic after monsters came from the other worlds.")
speak("Elder", "There is more. Many say that before the sages sealed the gates of Hero, they opened a back entrance with four otherworldly artifacts.")
speak(hero, "That's the legend.")
speak("Elder", "I'm one of the few alive who remember when the gates were sealed, so I know it happened.")
speak("Elder", "In fact, they gave each of the city elders one of the four otherworldly artifacts, so if we wished, we could reopen the way to Hero.")
speak(hero, "So you have one of these artifacts?")
speak("Elder", "Yes. My artifact is actually a set of items, magical sending stones that let the owners talk across great distances.")
speak("Elder", "I gave one of these sending stones to Jonas and Janine before they left. Now I only have one left, or I would give you one as well.")
speak(hero, "How are we supposed to get to Hero without one of these sending stones?")
speak("Elder", "There were four in the set, originally. Maybe you can find one somewhere else.")
speak(hero, "Any other advice?")
speak("Elder", "There is a city on the river south of here. The governor there may be willing to give up his artifact. It's worth a try.")
speak(hero, "Thank you, Elder.")
speak("Elder", "Tell me right away if you hear anything of Jonas and Janine.")
sceneSwitch('opening_talked_elder', true)
