local hero1 = getHero(0).getName()
local hero2 = getHero(2).getName()

speak(hero1, "The door is sealed.")
speak(hero2, "Perhaps try the sending stone?")
speak(hero1, "Okay, although I'm not quite sure how to use it.")
speak('David', "Press this here, then speak.")
speak(hero1, "Hello?")
speak('????', "Greetings, adventurer, and welcome to the town of Hero.")

fade('white')
wait(1.0)
teleport('world1/demo.tmx', 11, 11, 'NORTH', false)
fade('normal')
wait(1.0)
speak("This is the end of the SaGa4 demo. We've hope you've enjoyed playing the game so far, and hope you follow the game for more updates...")
speak("...and the true secret of Hero!")
fade('white')
wait(1.0)
teleport('world1/herocave03.tmx', 14, 16, 'SOUTH', false)
fade('normal')
